import React from 'react'
import state from './index.state'
export const columns = [
    {
        title : '名称',
        dataIndex : 'title',
        align : 'center'
    },
    // {
    //     title : '坐标',
    //     dataIndex : 'lng',
    //     align : 'center'
    // },
    {
        title : '地址',
        dataIndex : 'address',
        align : 'center'
    },
    {
        title : '单价',
        dataIndex : 'unitprice',
        align : 'center'
    },
    {
        title : '总价',
        dataIndex : 'totalprice',
        align : 'center'
    },
    {
        title : '总面积',
        dataIndex : 'area',
        align : 'center'
    },
    {
        title : '始建年份',
        dataIndex : 'year',
        align : 'center'
    },
    {
        title : '房型',
        dataIndex : 'type',
        align : 'center'
    },
    {
        title : '所在楼层',
        dataIndex : 'floor',
        align : 'center'
    },
    // {
    //     title : '梯户比例',
    //     dataIndex : 'proportion',
    //     align : 'center'
    // },
    {
        title : '配备电梯',
        dataIndex : 'hasElevator',
        align : 'center'
    },
    // {
    //     title : '装修情况',
    //     dataIndex : 'decorationSituation',
    //     align : 'center'
    // },
    {
        title : '房屋年限',
        dataIndex : 'yearLimit',
        align : 'center'
    },
    {
        title : '抵押信息',
        dataIndex : 'mortgageInfo',
        align : 'center'
    },
    {
        title : '产权所属',
        dataIndex : 'property',
        align : 'center'
    },
    {
        title : '交易权属',
        dataIndex : 'deal',
        align : 'center'
    },
    {
        title : '距地铁距离',
        dataIndex : 'railwayDistance',
        align : 'center'
    },
    {
        title : '房型图',
        dataIndex : 'typeImg',
        align : 'center'
    },
    {
        title : '来源',
        dataIndex : 'source',
        align : 'center'
    },
]




export const fixedInfo = [
    {
        key : 'a',
        title : '公司',
        lng : [121.462435, 31.189479],
        address : '平安大厦',
        unitprice : '-',
        totalprice : '-',
        area : '-',
        year : '-',
        type : '-',
        floor : '-',
        proportion : '-',
        hasElevator: '是',
        decorationSituation : '-',
        yearLimit : '-',
        mortgageInfo : '-',
        property : '-',
        deal : '-',
        railwayDistance : '-',
        typeImg : '-',
        source : '-',
    },
    {
        key : 'b',
        title : '家',
        lng : [121.303,31.304206],
        address : '星信名邸',
        unitprice : '-',
        totalprice : '-',
        area : '-',
        year : '-',
        type : '-',
        floor : '-',
        proportion : '-',
        hasElevator: '是',
        decorationSituation : '-',
        yearLimit : '-',
        mortgageInfo : '-',
        property : '-',
        deal : '-',
        railwayDistance : '-',
        typeImg : '-',
        source : '-',
    },
    {
        key : 'c',
        title : '老婆妈家',
        lng : [121.403175,31.267628],
        address : '达安春之声',
        unitprice : '-',
        totalprice : '-',
        area : '-',
        year : '-',
        type : '-',
        floor : '-',
        proportion : '-',
        hasElevator: '是',
        decorationSituation : '-',
        yearLimit : '-',
        mortgageInfo : '-',
        property : '-',
        deal : '-',
        railwayDistance : '-',
        typeImg : '-',
        source : '-',
    },
    {
        key : 'd',
        title : '妈家',
        lng : [121.418930,31.127928],
        address : '中梅苑东区',
        unitprice : '-',
        totalprice : '-',
        area : '-',
        year : '-',
        type : '-',
        floor : '-',
        proportion : '-',
        hasElevator: '是',
        decorationSituation : '-',
        yearLimit : '-',
        mortgageInfo : '-',
        property : '-',
        deal : '-',
        railwayDistance : '-',
        typeImg : '-',
        source : '-',
    },
    {
        key : 'e',
        title : '完美世界',
        lng : [121.530670,31.252476],
        address : '渔人码头',
        unitprice : '-',
        totalprice : '-',
        area : '-',
        year : '-',
        type : '-',
        floor : '-',
        proportion : '-',
        hasElevator: '是',
        decorationSituation : '-',
        yearLimit : '-',
        mortgageInfo : '-',
        property : '-',
        deal : '-',
        railwayDistance : '-',
        typeImg : '-',
        source : '-',
    },
    {
        key : 'f',
        title : '老婆公司',
        lng : [121.372759,31.234586],
        address : '金沙商务广场',
        unitprice : '-',
        totalprice : '-',
        area : '-',
        year : '-',
        type : '-',
        floor : '-',
        proportion : '-',
        hasElevator: '是',
        decorationSituation : '-',
        yearLimit : '-',
        mortgageInfo : '-',
        property : '-',
        deal : '-',
        railwayDistance : '-',
        typeImg : '-',
        source : '-',
    },
]

export const homedata = [
    {
        key : '1',
        title : '程桥一村',
        lng : [121.368373,31.188572],
        address : '长宁 西郊 中环至外环 近十号线',
        unitprice : '64984元/平',
        totalprice : '260万',
        area : '40.01m²',
        year : '1985年',
        type : '1室1厅',
        floor : '中楼层/共5层',
        proportion : '一梯四户',
        hasElevator: '否',
        decorationSituation : '简装',
        yearLimit : '未满两年',
        mortgageInfo : '无抵押',
        property : '非共有',
        deal : '售后公房',
        railwayDistance : '距离上海动物园站345米',
        typeImg : <img src = {require('./components/img/chengqiaoyicun.png').default} className = 'typeImg' onClick = {() => {state.showImg('chengqiaoyicun.png')}} />,
        source : '链家',
    },
    {
        key : '2',
        title : '沁春园一村',
        lng : [121.378983,31.097126],
        address : '闵行 莘庄 外环外',
        unitprice : '64373元/平',
        totalprice : '290万',
        area : '45.05m²',
        year : '1997年',
        type : '1室1厅',
        floor : '高楼层/共6层',
        proportion : '一梯四户',
        hasElevator: '否',
        decorationSituation : '精装',
        yearLimit : '满五年',
        mortgageInfo : '有抵押20万 业主自还',
        property : '共有',
        deal : '商品房',
        railwayDistance : '距离春申路5号线站985米',
        typeImg : <img src = {require('./components/img/qinchunyuan.png').default} className = 'typeImg' onClick = {() => {state.showImg('qinchunyuan.png')}} />,
        source : '链家',
    },
    {
        key : '3',
        title : '奥林匹克花园',
        lng : [121.325886,31.150233],
        address : '松江 九亭 外环外',
        unitprice : '53818元/平',
        totalprice : '289万',
        area : '53.7m²',
        year : '2005年',
        type : '1室1厅',
        floor : '低楼层/共4层',
        proportion : '一梯五户',
        hasElevator: '否',
        decorationSituation : '精装',
        yearLimit : '无数据',
        mortgageInfo : '无抵押',
        property : '共有',
        deal : '商品房',
        railwayDistance : '距离中春路9号线站949米',
        typeImg : <img src = {require('./components/img/aolinpikehuayuan.png').default} className = 'typeImg' onClick = {() => {state.showImg('aolinpikehuayuan.png')}} />,
        source : '链家',
    },
    {
        key : '4',
        title : '三门路510弄',
        lng : [121.490618,31.311163],
        address : '杨浦 五角场 中环至外环',
        unitprice : '65978元/平',
        totalprice : '268万',
        area : '40.62m²',
        year : '1995年',
        type : '1室1厅',
        floor : '中楼层/共7层',
        proportion : '一梯四户',
        hasElevator: '否',
        decorationSituation : '毛坯',
        yearLimit : '满五年',
        mortgageInfo : '无抵押',
        property : '非共有',
        deal : '商品房',
        railwayDistance : '距离江湾镇3号线站932米',
        typeImg : <img src = {require('./components/img/sanmenlu.png').default} className = 'typeImg' onClick = {() => {state.showImg('sanmenlu.png')}} />,
        source : '链家',
    },
    {
        key : '5',
        title : '控江东三村',
        lng : [121.534085,31.286524],
        address : '杨浦 黄兴公园 内环至中环',
        unitprice : '58120元/平',
        totalprice : '238万',
        area : '40.95m²',
        year : '1993年',
        type : '1室1厅',
        floor : '中楼层/共6层',
        proportion : '一梯五户',
        hasElevator: '否',
        decorationSituation : '简装',
        yearLimit : '满两年',
        mortgageInfo : '无抵押',
        property : '共有',
        deal : '商品房',
        railwayDistance : '距离延吉中路8号线站279米',
        typeImg : <img src = {require('./components/img/kongjiangdongsancun.png').default} className = 'typeImg' onClick = {() => {state.showImg('kongjiangdongsancun.png')}} />,
        source : '链家',
    },
    {
        key : '6',
        title : '上大东村',
        lng : [121.460499,31.277631],
        address : '静安 大宁 内环至中环',
        unitprice : '57607元/平',
        totalprice : '245万',
        area : '42.53m²',
        year : '1993年',
        type : '1室1厅',
        floor : '高楼层/共6层',
        proportion : '一梯两户',
        hasElevator: '否',
        decorationSituation : '简装',
        yearLimit : '满五年',
        mortgageInfo : '无抵押',
        property : '非共有',
        deal : '商品房',
        railwayDistance : '距离延长路1号线站953米',
        typeImg : <img src = {require('./components/img/shangdadongcun.png').default} className = 'typeImg' onClick = {() => {state.showImg('shangdadongcun.png')}} />,
        source : '链家',
    },
    {
        key : '7',
        title : '上大东村',
        lng : [121.460499,31.277631],
        address : '静安 大宁 内环至中环',
        unitprice : '62178元/平',
        totalprice : '265万',
        area : '42.62m²',
        year : '1993年',
        type : '1室1厅',
        floor : '低楼层/共6层',
        proportion : '一梯两户',
        hasElevator: '否',
        decorationSituation : '简装',
        yearLimit : '未满两年',
        mortgageInfo : '无抵押',
        property : '非共有',
        deal : '商品房',
        railwayDistance : '距离延长路1号线站953米',
        typeImg : <img src = {require('./components/img/shangdadongcun.png').default} className = 'typeImg' onClick = {() => {state.showImg('shangdadongcun.png')}} />,
        source : '链家',
    },
    {
        key : '8',
        title : '华松西区',
        lng : [121.357506,31.210718],
        address : '长宁 北新泾 中环至外环',
        unitprice : '58140元/平',
        totalprice : '255万',
        area : '43.86m²',
        year : '1995年',
        type : '1室1厅',
        floor : '中楼层/共7层',
        proportion : '一梯四户',
        hasElevator: '否',
        decorationSituation : '简装',
        yearLimit : '满两年',
        mortgageInfo : '无抵押',
        property : '非共有',
        deal : '商品房',
        railwayDistance : '距离淞虹路2号线站1104米',
        typeImg : <img src = {require('./components/img/huasongxiqu.png').default} className = 'typeImg' onClick = {() => {state.showImg('huasongxiqu.png')}} />,
        source : '链家',
    },
    {
        key : '9',
        title : '乾溪新村',
        lng : [121.407700,31.304440],
        address : '宝山 大场镇 中环至外环',
        unitprice : '51904元/平',
        totalprice : '255万',
        area : '49.13m²',
        year : '1994年',
        type : '1室1厅',
        floor : '低楼层/共6层',
        proportion : '一梯两户',
        hasElevator: '否',
        decorationSituation : '精装',
        yearLimit : '满两年',
        mortgageInfo : '无抵押',
        property : '共有',
        deal : '商品房',
        railwayDistance : '距离场中路7号线站358米',
        typeImg : <img src = {require('./components/img/qianxixincun.png').default} className = 'typeImg' onClick = {() => {state.showImg('qianxixincun.png')}} />,
        source : '链家',
    },
    
]